[package]
name = "fetch"
version = "0.9.7"
authors = ["Phate6660 <ValleyKnight@protonmail.com>"]
edition = "2018"

[dependencies]
prettytable-rs = "^0.8"

[dependencies.clap]
git = "https://github.com/clap-rs/clap.git"
