[package]
name = "fetch"
version = "1.4.0"
authors = ["Phate6660 <ValleyKnight@protonmail.com>"]
edition = "2018"

[dependencies]
bytecount = "0.5.1"
clap = "~2.33"
itoa = "0.4"
prettytable-rs = "^0.8"
pwd = "1.3"
uptime_lib = "0.1.0"
