[package]
name = "fetch"
version = "0.9.3"
authors = ["Phate6660 <afauacakagaoaoagalae@gmail.com>"]
edition = "2018"

[dependencies]
prettytable-rs = "^0.8"

[dependencies.clap]
git = "https://github.com/clap-rs/clap.git"
