[package]
name = "fetch"
version = "1.3.8"
authors = ["Phate6660 <ValleyKnight@protonmail.com>"]
edition = "2018"

[dependencies]
prettytable-rs = "^0.8"
clap = "~2.33"
pwd = "1.3"
bytecount = "0.5.1"
