[package]
name = "rsfetch"
version = "1.9.0"
authors = ["Phate6660 <ValleyKnight@protonmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
libc = "0.2.66"
clap = "^2.33"
dirs = "1.0"
log = "0.4"
pretty_env_logger = "0.3"
prettytable-rs = "0.8"
reqwest = "0.9"
snafu = "0.3"
